### ISSUE TITLE
big database updates give Server Error

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#203]
Try to duplicate watchlist [1177](https://lasair-ztf.lsst.ac.uk/watchlists/1177/) gives Internal Server Error with `MySQLInterfaceError: wsrep_max_ws_rows exceeded`

The code is [here](https://github.com/lsst-uk/lasair4/blob/main/webserver/lasair/apps/watchlist/views.py#L220-L231)

Either change the limit `wsrep_max_ws_rows` or do this in batches. The same problem will happen when a watchlist/watchmap is deleted.

**Comment by genghisken** [comment]
This is a new one on me!

Let's see whether or not this can be done in batches. We can add the max rows setting (what is the default??), but a) it will probably get broken again in the future, and b) the setting is not deployable (yet) via Ansible, since the database instances are actually created by ClusterControl.  (The latter is not impossible to do, just fiddly. I.e. Deploy DB instances then get Ansible to update the created my.cnf files.)

**Comment by RoyWilliams** [comment]
Thats wierd it says [here](https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_max_ws_rows) that "default value has been changed to 0, which essentially allows writesets to be any size."

**Comment by genghisken** [comment]
It's not set to the default value. The ClusterControl module must have set the values which are currently:
```
# Maximum number of rows in write set
wsrep_max_ws_rows=131072

# Maximum size of write set
wsrep_max_ws_size=1073741824
```

**Comment by RoyWilliams** [comment]
ACTION:
Find out what version of Galera is being deployed in gkansible.gkservercolleciton, etc.
Can we update the Galera version without breaking it? 
Does changing the version actually change the value of wsrep_max_ws_rows??
If above is not possible - can we create an Ansible script to update the config post deployment by clustercontrol?

**Comment by RoyWilliams** [comment]
ACTION for Roy:
Define variable in settings TOO_BIG_WATCHLIST = 1000000
Make a test for the number of cones and reject watchlists bigger than this
lasair4/webserver/lasair/apps/watchlist/views.py line 94

**Comment by genghisken** [comment]
Took some digging. It looks like ClusterControl stores its config files in:

```
/usr/share/cmon/templates/my.cnf.mdb10x-galera
```

So EITHER we update that file immediately after ClusterControl has been installed and BEFORE the databases are deployed OR we update the my.cnf on the target nodes.  I vote for the latter, since the former only works for the virgin install and not for any updates.

The temporary table size setting previously deployed should also be stored here.

**Comment by genghisken** [comment]
Still working on this. I can only test it if I have an actual Galera cluster I can experiment with, so I'm setting one up locally.  The config will be altered post installation.

**Comment by genghisken** [comment]
Ansible scripts have been changed to update the config after deployment of the database nodes. This goes for this issue and the temporary table size too.
