### ISSUE TITLE
ALPHA TEST 02. Password Reset.

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#77]
Navigate to <https://lasair-dev.lsst.ac.uk> and if you are logged in please log out.

Attempt to log in again, but pretend you have forgotten your password. 

CHECKLIST:

- Did you receive a password reset email?
- Did the email land in your inbox or spam?
- How long did the email take to arrive?
- Were you able to successfully reset your password? 
- Any other feedback?

Things to note:
- Reset password emails are successfully received by my QUB account
- I have struggled a lot of the day trying to get the reset password emails to be received by an account registered with a Gmail account. No luck yet. A google search finds many with the same issue. Can someone else please test with their Gmail address?

**Comment by gpfrancis** [comment]
Got the password reset email OK after about a minute (epcc.ed.ac.uk address)
Password reset page took a long time to load (~30s)
Attempting to reset password clears the page without any clear indication of failure or success
It turns out it failed
Tried again with a new password reset email and on the second attempt it all worked fine (password reset page loaded much faster too)

**Comment by smarttgit** [comment]
went to https://lasair-dev.lsst.ac.uk
I wasn't logged in, so I went to "Sign In"
Just hangs now - doesn't sign me in.

**Comment by mschwamb** [comment]
" Please check your email for instructions on how to reset your password. " "If your email is associated with a registered account, you will will receive an email with instructions on how to check your password"

**Comment by gpfrancis** [comment]
Tried to create a new account with my gmail address
Filled in details on registration page and clicked "sign up"
It sits there for about a minute before returning to the same point with no obvious error
Aside: trying to open the privacy policy in a new tab failed
Tried again with a different username in case that was the problem and now I get "error verifying captcha, please try again"
Tried again and it worked this time
Was able to log in, log out, request a password reset email for the gmail account
After a few minutes the reset email has not turned up, will update if this changes

**Comment by gpfrancis** [comment]
Also, unless I'm missing something it appears that the privacy policy it available only at sign up - it should be accessible somewhere else, even if in the docs rather than the main web interface.

**Comment by thespacedoctor** [comment]
Well that didn't go to plan! Sorry @smarttgit and @gpfrancis ... the webserver was not in a good state. A bounce may have fixed these issues.

@mschwamb I will add your suggested change.
@gpfrancis The privacy notice is found in a drop-down modal on the login screen. I will also link it somewhere more accessible as you suggest.
@gpfrancis I will add a password reset success message when page reloads

**Comment by gpfrancis** [comment]
@thespacedoctor

I don't see a privacy notice available on the login page, drop down or otherwise, only on the registration page. Also I see no good reason from a UI POV for the link not to point to the actual privacy policy so that it can be linked to, opened in a new window/tab etc. although whether this is technically easy to do I don't know.

The problem was not the lack of a password reset success message - I got one of those when it did work - the problem was the lack of a failure message when it didn't.

**Comment by mschwamb** [comment]
I did not get reset emails yesterday, but it is working for me now. 

The system let me resit to the current password. Is that okay?

**Comment by thespacedoctor** [comment]
Thanks Meg. Typo fixed.

Gareth and I solved (perhaps temporarily) the Gmail issue. Changing the source email address to the `lsst.ac.uk` domain seems to appease the Gmail server gods for now.

Other updates include:

* Lasair Privacy Policy is now linked to a dedicated page <https://lasair-dev.lsst.ac.uk/privacy>. I will add a link in the footer in due course.
* Validation errors now appear in the password reset form
<img width="908" alt="image" src="https://user-images.githubusercontent.com/3385557/208672372-fe601cb8-91bc-457e-8d9e-b5c51fd227eb.png">
* A password reset success message is also presented to the user
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/3385557/208672325-5fd25dd9-6e36-4b84-87a3-f349128da0fe.png">

**Comment by mschwamb** [comment]
From the reset email, the link appears to be valid forever. Is there a time limit, like the link works for an hour and this is unusable to reset the password? If so, it would be good to add that to the email text with the link.

One other thing. Since it wasn't working, it wasn't clear who to contact if I didn't get any email.

**Comment by chrisfrohmaier** [comment]
The password reset email went to my spam and my University auto-blocks links in those emails (Outlook). Not a problem to flag as "Not Junk" and move to my Inbox though. Password reset was successful.
Email took 2 minutes to arrive.

Safari 16.1. macOS 12.6.1

**Comment by gpfrancis** [comment]
If I try to log in with the wrong password I don't get an error, it just appears to be loading the same page for a long time.

**Comment by thespacedoctor** [comment]
Fixed.

**Comment by thespacedoctor** [comment]
Fixed.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/3385557/208726693-55dd32ac-aec6-4884-8d24-ad75f54df955.png">

**Comment by andyxerxes** [comment]
Using the account set up with my ROE email address, everything worked fine - got email, clicked through, set new password, logged in with new password

Using my gmail account, the email hadn't arrived five minutes later...

**Comment by thespacedoctor** [comment]
Privacy link is now accessible from the footer of every page and the Gmail issues are somewhat resolved (thanks to @gpfrancis and @RoyWilliams).
