### ISSUE TITLE
Lightcurve features reported in database need to be calculated on full lightcurves

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#89]
For example, `JDMIN` needs to be calculated from the full lightcurve. JDMIN currently reports the first detection in the most recent alert packet. I understand this is not a trivial change, but users assume features in the database relate to the full LCs.

**Comment by RoyWilliams** [comment]
We can't go reading cassandra for every alert to figure out JDMIN and do all the features. The whole basis of our scalable architecture is that doubling the number of filter nodes doubles the speed, but we lose that completely if everyone is hammering on cassandra to get full lightcurves. How about we just dump JDMIN since its almost always 30 days, its confusing, and its useless?

**Comment by RoyWilliams** [comment]
The target of course is LSST, with a year in the alert. So maybe JDMIN is useful, as long as our users understand that it and everything else is computed from a finite recent subset of the full lightcurve.

**Comment by thespacedoctor** [comment]
The true JDMIN should never change, so only ever needs to be calculated once. The same is true for say the last non-detection before the discovery. We could have columns for 'fixed attributes' that need set once and forgotten? Worth a discussion :)

**Comment by RoyWilliams** [comment]
Good idea! Lets see ... Currently all the features are computed from the short lightcurve and go into the database with a REPLACE operation. I think you are suggesting a second object table (maybe fixed_objects) with INSERT only once when that objectID is not present in the main objects table.
